version: "3.7"
services: 
  mysql:
    image: iwantm/springpetclinicdb
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
      

  back-end:
    image: iwantm/springpetclinicrest
    ports:
    - target: 9966
      published: 9966
      protocol: tcp


  front-end:
    image: iwantm/springpetclinicangular
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    depends_on:
    - back-end 