apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  labels:
    app: back-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  back-end
  template:
    metadata:
      labels:
        app:  back-end
    spec:
      containers:
        - name:  back-end
          image: qateam1/springclinicrest:latest
          ports:
          - name: back-end
            containerPort: 9966
---
apiVersion: v1
kind: Service
metadata:
   name:  back-end   
spec:
   selector:
     app:  back-end
   ports:
     - protocol: TCP
       port: 9966
       targetPort: 9966

