apiVersion: apps/v1
kind: Deployment
metadata:
  name: springclinicrest
  labels:
    app: springclinicrest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springclinicrest
  template:
    metadata:
      labels:
        app: springclinicrest
    spec:
      containers:
        - name: springclinicrest
          image: qateam1/springclinicrest:latest
          ports:
          - name: rest-port
            containerPort: 9966

---

apiVersion: v1
kind: Service
metadata:
   name: springclinicrest
   labels:
     app: springclinicrest      
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 9966
       targetPort: 9966
   selector:
     app: springclinicrest