apiVersion: v1
kind: Service
metadata:
   name: springclinicangular
   labels:
     app: springclinicangular  
   namespace: staging    
spec:
   ports:
     - protocol: TCP
       port: 8080
       targetPort: 8080
   selector:
     app: springclinicangular