apiVersion: apps/v1
kind: Deployment
metadata:
  name: springclinicangular
  labels:
    app: springclinicangular
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springclinicangular
  template:
    metadata:
      labels:
        app: springclinicangular
    spec:
      containers:
        - name: springclinicangular
          image: qateam1/springclinicangular:latest
          ports:
          - name: angular-port
            containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
   name: springclinicangular
   labels:
     app: springclinicangular      
spec:
   ports:
     - protocol: TCP
       port: 8080
       targetPort: 8080
   selector:
     app: springclinicangular