apiVersion: v1
kind: Service
metadata:
   name: springclinicangular
   namespace: live 
   labels:
     app: springclinicangular      
spec:
   ports:
     - protocol: TCP
       port: 8080
       targetPort: 8080
   selector:
     app: springclinicangular