- hosts: all
  become: yes
  tasks:
    - name: "Add nodejs apt key"
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: "Add nodejs 10.x ppa for apt repo"
      apt_repository:
        repo: deb https://deb.nodesource.com/node_10.x bionic main
        update_cache: yes

    - name: "Install nodejs"
      apt:
        update_cache: yes
        name: nodejs
        state: present

    - name: "Install NPM-distributed command-line tools"
      npm:
        global: yes
        name: "{{ item }}"
      with_items:
        - firebase-tools

    - name: "Install Chromium"
      snap:
        name:
          - chromium

    - name: "Install Chromium-Browser"
      apt:
        name: chromium-browser
        state: present
        update_cache: yes
      become: yes

    - name: "Clone git repository"
      git:
        repo: https://github.com/thomas-hennessy-work/QA-Final-Project.git
        version: testing
        dest: /home/tom/QA-Final-Project
        accept_hostkey: yes
        force: yes

    - name: Changing perm of "QA-Final-Project/spring-petclinic-angular/installE2EPackages.sh", adding "+x"
      file:
        dest: QA-Final-Project/spring-petclinic-angular/installE2EPackages.sh
        mode: a+x

    #- name: Go to the folder and execute command
      #command: chdir=QA-Final-Project/spring-petclinic-angular/ ls
      #ansible.builtin.shell: pwd

    #- name: "Change the working directory to angular and execute install e2e script"
      #ansible.builtin.shell: QA-Final-Project/spring-petclinic-angular/installE2EPackages.sh #>> e2eLogs.txt
      #ansible.builtin.shell: pwd
      #args:
        #chdir: QA-Final-Project/spring-petclinic-angular
        #chdir: .

    - name: "Change the working directory to angular and execute install e2e script"
      shell: /home/tom/QA-Final-Project/spring-petclinic-angular/installE2EPackages.sh
      args:
        chdir: /home/tom/QA-Final-Project/spring-petclinic-angular
      become: true
      become_user: tom
      